spring:

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: patient-service
              uri: lb://PATIENT-SERVICE
              predicates:
                - Path=/api/v1/patient/**

            - id: doctor-service
              uri: lb://DOCTOR-SERVICE
              predicates:
                - Path=/api/v1/doctor/**

            - id: appointment-service
              uri: lb://APPOINTMENT-SERVICE
              predicates:
                - Path=/api/v1/appointments/**

          default-filters:
            - PreserveHostHeader

          globalcors:
            cors-configurations:
              '[/**]':
                allowedOrigins: "*"
                allowed-methods: "*"
                allowed-headers: "*"

server:
  port: 7001